server:
  port: 12000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        route:
          - id: web
            uri: http://127.0.0.1:9102
            predicates:
              - Path=/web/**
          #            filters:
          #              - StripPrefix=1
  eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.43.110:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.yaml.instance_id:${server.port}}
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10