server:
  port: 12000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: springboot-init
          uri: lb://springboot-init
          predicates:
            - Path=/user/**
#          filters:
#            - StripPrefix=1
eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.43.110:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.yaml.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
